project:
  type: default
  output-dir: _site

format:
  revealjs:
    theme: [default, assets/css/custom.scss]
    lang: es
    slide-number: true
    controls: true
    progress: true
    transition: fade
    background-transition: fade
    center: false
    width: 1600
    height: 900
    margin: 0.05
    min-scale: 0.2
    max-scale: 2.0
    html-math-method: plain
    preview-links: false
    chalkboard: false
    incremental: false
    navigation-mode: linear
    history: false
    hash: false
    controls-layout: edges
    controls-back-arrows: faded
    auto-animate-duration: 0.6
    include-after-body: assets/includes/scripts.html

execute:
  echo: false
  warning: false
  message: false
